[package]
name = "datalens-indexer"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
datalens-client = { path = "../client" }
datalens-core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.11.0"
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "sqlite"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
toml.workspace = true
