[package]
name = "datalens-indexer"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-graphql.workspace = true
async-graphql-axum.workspace = true
axum.workspace = true
datalens-client = { path = "../client" }
datalens-core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
sha2 = "0.11.0"
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "tls-rustls-ring-native-roots", "sqlite", "postgres"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
toml.workspace = true

[dev-dependencies]
tower.workspace = true
