[package]
name = "datalens-bridge-processor"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-graphql.workspace = true
datalens-core = { path = "../../crates/core" }
datalens-indexer = { path = "../../crates/indexer" }
serde.workspace = true
serde_json.workspace = true
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "tls-rustls-ring-native-roots", "sqlite"] }
tokio.workspace = true
