[package]
name = "datalens-warmup"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
datalens-chain = { path = "../../chain" }
datalens-core = { path = "../../core" }
datalens-metrics = { path = "../../metrics" }
datalens-storage = { path = "../../storage" }
datalens-writer = { path = "../writer" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
datalens-executor = { path = "../executor" }
datalens-planner = { path = "../planner" }
datalens-solana = { path = "../../adapters/solana" }
datalens-tron = { path = "../../adapters/tron" }
