[package]
name = "datalens-evm"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
datalens-chain = { path = "../../chain" }
datalens-core = { path = "../../core" }
datalens-storage = { path = "../../storage" }
datalens-writer = { path = "../../runtime/writer" }
log.workspace = true
reqwest.workspace = true
serde_json.workspace = true
sha3 = "0.11.0"

[dev-dependencies]
datalens-chain-conformance = { path = "../../testing/chain-conformance" }
