[package]
name = "datalens-evm"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
datalens-chain = { path = "../../chain" }
datalens-core = { path = "../../core" }
log.workspace = true
reqwest.workspace = true
serde_json.workspace = true

[dev-dependencies]
datalens-chain-conformance = { path = "../../testing/chain-conformance" }
