[package]
name = "datalens-executor"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
datalens-chain = { path = "../chain" }
datalens-core = { path = "../core" }
datalens-metrics = { path = "../metrics" }
datalens-planner = { path = "../planner" }
datalens-storage = { path = "../storage" }
datalens-writer = { path = "../writer" }
log.workspace = true
serde_json.workspace = true
