[package]
name = "datalens-api"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
datalens-core = { path = "../core" }
datalens-planner = { path = "../planner" }
datalens-storage = { path = "../storage" }
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
