[package]
name = "datalens-api"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
datalens-chain = { path = "../chain" }
datalens-core = { path = "../core" }
datalens-executor = { path = "../executor" }
datalens-metrics = { path = "../metrics" }
datalens-planner = { path = "../planner" }
datalens-storage = { path = "../storage" }
datalens-writer = { path = "../writer" }
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true

[dev-dependencies]
datalens-client = { path = "../client" }
tower.workspace = true
