name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check workspace
        run: just check

      - name: Run clippy
        run: just clippy
